name: Docker Image Build with Timestamp Tag

on:
  workflow_dispatch:  # 👈 manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag with compact timestamp
      id: vars
      run: echo "tag=$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build . -t user-management:${{ steps.vars.outputs.tag }}

    - name: Tag image for Docker Hub
      run: |
        docker tag user-management:${{ steps.vars.outputs.tag }} vaibhavb1996/user-management:${{ steps.vars.outputs.tag }}

    - name: Push Docker image
      run: |
        docker push vaibhavb1996/user-management:${{ steps.vars.outputs.tag }}
