name: Docker Image Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on Git tags like v1.0.0, v2.3.4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      id: tag
      run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build . -t user-management:${{ steps.tag.outputs.version }}

    - name: Tag Docker image for Docker Hub
      run: |
        docker tag user-management:${{ steps.tag.outputs.version }} vaibhavb1996/user-management:${{ steps.tag.outputs.version }}
        docker tag user-management:${{ steps.tag.outputs.version }} vaibhavb1996/user-management:latest

    - name: Push Docker images to Docker Hub
      run: |
        docker push vaibhavb1996/user-management:${{ steps.tag.outputs.version }}
        docker push vaibhavb1996/user-management:latest
